-- Decompiled using luadec 2.2 rev: 5d67c74 for Lua 5.3 from https://github.com/viruscamp/luadec
-- Command line: C:\Users\nikur\Documents\2.8.50_dev_lua\MiHoYoBinData\AvatarTalentExcelConfig.luac 

-- params : ...
-- function num : 0 , upvalues : upval_0
local l_0_0 = {}
l_0_0.TALENT_POINT_NONE = 0
l_0_0.TALENT_POINT_SMALL = 1
l_0_0.TALENT_POINT_BIG = 2
upval_0.TalentPointType = l_0_0
upval_0.TalentFilterCond, l_0_0 = l_0_0, {TALENT_FILTER_NONE = 0, TALENT_FILTER_FIRE_AVATAR = 1, TALENT_FILTER_ELEC_AVATAR = 2, TALENT_FILTER_WATER_AVATAR = 3, TALENT_FILTER_GRASS_AVATAR = 4, TALENT_FILTER_WIND_AVATAR = 5, TALENT_FILTER_ICE_AVATAR = 6, TALENT_FILTER_ROCK_AVATAR = 7}
upval_0.ProudSkillType, l_0_0 = l_0_0, {PROUD_SKILL_NONE = 0, PROUD_SKILL_CORE = 1, PROUD_SKILL_INHERENT = 2, PROUD_SKILL_ACTIVE = 3}
upval_0.EffectTargetType, l_0_0 = l_0_0, {EFFECT_TARGET_NONE = 0, EFFECT_TARGET_SOLO = 1, EFFECT_TARGET_TEAM = 2}
upval_0.ProudLifeEffectType, l_0_0 = l_0_0, {PROUD_EFFECT_NONE = 0, PROUD_EFFECT_COMBINE_RETURN_MATERIAL = 1, PROUD_EFFECT_COMBINE_MULTIPLY_OUTPUT = 2, PROUD_EFFECT_COMBINE_EXTRA_OUTPUT = 3, PROUD_EFFECT_COMBINE_ADD_EXTRA_PROB = 4, PROUD_EFFECT_COOK_EXTRA_PROFICIENCY = 101, PROUD_EFFECT_COOK_WIDEN_JUDGE_AREA = 102, PROUD_EFFECT_COOK_ADD_BONUS_PROB = 103, PROUD_EFFECT_FORGE_REDUCE_TIME = 203, PROUD_EFFECT_FORGE_ADD_EXTRA_PROB = 204}

