-- Decompiled using luadec 2.2 rev: 5d67c74 for Lua 5.3 from https://github.com/viruscamp/luadec
-- Command line: C:\Users\nikur\Documents\3.3.51_lua\MiHoYoBinData\CommonScriptConfig.luac 

-- params : ...
-- function num : 0 , upvalues : upval_0
local l_0_0 = {}
l_0_0.REGION_NONE = 0
l_0_0.REGION_SPHERE = 1
l_0_0.REGION_CUBIC = 2
upval_0.RegionShape = l_0_0
upval_0.EventType, l_0_0 = l_0_0, {EVENT_NONE = 0, EVENT_ANY_MONSTER_DIE = 1, EVENT_ANY_GADGET_DIE = 2, EVENT_VARIABLE_CHANGE = 3, EVENT_ENTER_REGION = 4, EVENT_LEAVE_REGION = 5, EVENT_GADGET_CREATE = 6, EVENT_GADGET_STATE_CHANGE = 7, EVENT_DUNGEON_SETTLE = 8, EVENT_SELECT_OPTION = 9, EVENT_CLIENT_EXECUTE = 10, EVENT_ANY_MONSTER_LIVE = 11, EVENT_SPECIFIC_MONSTER_HP_CHANGE = 12, EVENT_CITY_LEVELUP_UNLOCK_DUNGEON_ENTRY = 13, EVENT_DUNGEON_BROADCAST_ONTIMER = 14, EVENT_TIMER_EVENT = 15, EVENT_CHALLENGE_SUCCESS = 16, EVENT_CHALLENGE_FAIL = 17, EVENT_SEAL_BATTLE_BEGIN = 18, EVENT_SEAL_BATTLE_END = 19, EVENT_GATHER = 20, EVENT_QUEST_FINISH = 21, EVENT_MONSTER_BATTLE = 22, EVENT_CITY_LEVELUP = 23, EVENT_CUTSCENE_END = 24, EVENT_AVATAR_NEAR_PLATFORM = 25, EVENT_PLATFORM_REACH_POINT = 26, EVENT_UNLOCK_TRANS_POINT = 27, EVENT_QUEST_START = 28, EVENT_GROUP_LOAD = 29, EVENT_GROUP_REFRESH = 30, EVENT_DUNGEON_REWARD_GET = 31, EVENT_SPECIFIC_GADGET_HP_CHANGE = 32, EVENT_MONSTER_TIDE_OVER = 33, EVENT_MONSTER_TIDE_CREATE = 34, EVENT_MONSTER_TIDE_DIE = 35, EVENT_SEALAMP_PHASE_CHANGE = 36}
upval_0.GadgetType, l_0_0 = l_0_0, {GADGET_NONE = 0, GADGET_WORLD_CHECT = 1, GADGET_DUNGEON_SECRET_CHEST = 2, GADGET_DUNGEON_PASS_CHEST = 3}
upval_0.GroupKillPolicy, l_0_0 = l_0_0, {GROUP_KILL_NONE = 0, GROUP_KILL_ALL = 1, GROUP_KILL_MONSTER = 2, GROUP_KILL_GADGET = 3, GROUP_KILL_NPC = 4}
upval_0.PlatformRotType, l_0_0 = l_0_0, {PLATFORM_ROT_NONE = 0, PLATFORM_ROT_SPEED = 1, PLATFORM_ROT_ROUND = 2}

