-- Decompiled using luadec 2.2 rev: 5d67c74 for Lua 5.3 from https://github.com/viruscamp/luadec
-- Command line: C:\Users\nikur\Documents\3.3.51_lua\MiHoYoBinData\DailyTaskExcelConfig.luac 

-- params : ...
-- function num : 0 , upvalues : upval_0
local l_0_0 = {}
l_0_0.DAILY_TASK_QUEST = 0
l_0_0.DAILY_TASK_SCENE = 1
upval_0.DailyTaskType = l_0_0
upval_0.ConditionType, l_0_0 = l_0_0, {CONDITION_NONE = 0, CONDITION_QUEST = 1, CONDITION_PLAYER_LEVEL = 2, CONDITION_VAR_EQ = 3, CONDITION_VAR_NE = 4, CONDITION_VAR_GT = 5, CONDITION_VAR_LT = 6}
upval_0.DailyTaskFinishType, l_0_0 = l_0_0, {DAILY_FINISH_NONE = 0, DAILY_FINISH_MONSTER_ID_NUM = 1, DAILY_FINISH_GADGET_ID_NUM = 2, DAILY_FINISH_MONSTER_CONFIG_NUM = 3, DAILY_FINISH_GADGET_CONFIG_NUM = 4, DAILY_FINISH_MONSTER_NUM = 5, DAILY_FINISH_CHEST_CONFIG = 6, DAILY_FINISH_GATHER = 7, DAILY_FINISH_CHALLENGE = 8}
upval_0.DailyTaskActionType, l_0_0 = l_0_0, {DAILY_TASK_ACTION_NONE = 0, DAILY_TASK_ACTION_SET_VAR = 1, DAILY_TASK_ACTION_INC_VAR = 2, DAILY_TASK_ACTION_DEC_VAR = 3, DAILY_TASK_ACTION_ADD_SURE_POOL = 4, DAILY_TASK_ACTION_ADD_POSSIBLE_POOL = 5}
upval_0.DailyTaskCondType, l_0_0 = l_0_0, {DAILY_TASK_COND_NONE = 0, DAILY_TASK_COND_VAR_EQ = 1, DAILY_TASK_COND_VAR_NE = 2, DAILY_TASK_COND_VAR_GT = 3, DAILY_TASK_COND_VAR_LT = 4}

