-- Decompiled using luadec 2.2 rev: 5d67c74 for Lua 5.3 from https://github.com/viruscamp/luadec
-- Command line: C:\Users\nikur\Documents\3.3.51_lua\MiHoYoBinData\EquipExcelConfig.luac 

-- params : ...
-- function num : 0 , upvalues : upval_0
local l_0_0 = {}
l_0_0.EQUIP_SLOT_NONE = 0
l_0_0.EQUIP_SLOT_WEAPON = 1
l_0_0.EQUIP_SLOT_BRACER = 2
l_0_0.EQUIP_SLOT_DRESS = 3
l_0_0.EQUIP_SLOT_SHOES = 4
l_0_0.EQUIP_SLOT_RING = 5
l_0_0.EQUIP_SLOT_NECKLACE = 6
upval_0.EquipSlotType = l_0_0
upval_0.AffixEffect, l_0_0 = l_0_0, {AFFIX_NONE = 0, AFFIX_ADD_ATTACK = 1, AFFIX_ADD_ATTACK_PERCENT = 2, AFFIX_ADD_DEFENSE = 3, AFFIX_ADD_DEFENSE_PERCENT = 4, AFFIX_ADD_MAX_HP = 5, AFFIX_ADD_MAX_HP_PERCENT = 6, AFFIX_ADD_MAX_STAMINA = 7, AFFIX_ADD_MAX_STAMINA_PERCENT = 8, AFFIX_ADD_STRIKE_PERCENT = 9, AFFIX_ADD_ANTI_STRIKE_PERCENT = 10, AFFIX_ADD_STRIKE_HURT_PERCENT = 11, AFFIX_ADD_NO_PROP_HURT_PERCENT = 12, AFFIX_SUB_NO_PROP_HURT_PERCENT = 13, AFFIX_ADD_FIRE_HURT_PERCENT = 14, AFFIX_SUB_FIRE_HURT_PERCENT = 15, AFFIX_ADD_WATER_HURT_PERCENT = 16, AFFIX_SUB_WATER_HURT_PERCENT = 17, AFFIX_ADD_GRASS_HURT_PERCENT = 18, AFFIX_SUB_GRASS_HURT_PERCENT = 19, AFFIX_ADD_ELEC_HURT_PERCENT = 20, AFFIX_SUB_ELEC_HURT_PERCENT = 21, AFFIX_ADD_WIND_HURT_PERCENT = 22, AFFIX_SUB_WIND_HURT_PERCENT = 23, AFFIX_SUB_SKILL_CD_PERCENT = 24, AFFIX_HP_RECOVER_PER_SECOND = 25, AFFIX_ADD_SPEED_PERCENT = 26}

