-- Decompiled using luadec 2.2 rev: 5d67c74 for Lua 5.3 from https://github.com/viruscamp/luadec
-- Command line: C:\Users\nikur\Documents\3.3.51_lua\MiHoYoBinData\GachaExcelConfig.luac 

-- params : ...
-- function num : 0 , upvalues : upval_0
local l_0_0 = {}
l_0_0.GACHA_TYPE_NEWBIE = 100
l_0_0.GACHA_TYPE_STANDARD = 200
l_0_0.GACHA_TYPE_STANDARD_AVATAR = 201
l_0_0.GACHA_TYPE_STANDARD_WEAPON = 202
l_0_0.GACHA_TYPE_ACTIVITY = 300
l_0_0.GACHA_TYPE_ACTIVITY_AVATAR = 301
l_0_0.GACHA_TYPE_ACTIVITY_WEAPON = 302
upval_0.GachaType = l_0_0
upval_0.GachaItemParentType, l_0_0 = l_0_0, {GACHA_ITEM_PARENT_INVALID = 0, GACHA_ITEM_PARENT_S5 = 1, GACHA_ITEM_PARENT_S4 = 2, GACHA_ITEM_PARENT_S3 = 3}
upval_0.GachaItemType, l_0_0 = l_0_0, {GACHA_ITEM_INVALID = 0, GACHA_ITEM_AVATAR_S5 = 11, GACHA_ITEM_AVATAR_S4 = 12, GACHA_ITEM_AVATAR_S3 = 13, GACHA_ITEM_WEAPON_S5 = 21, GACHA_ITEM_WEAPON_S4 = 22, GACHA_ITEM_WEAPON_S3 = 23, GACHA_ITEM_COMMON_MATERIAL = 31}
upval_0.GachaGuaranteeType, l_0_0 = l_0_0, {GACHA_GUARANTEE_NONE = 0, GACHA_GUARANTEE_SPECIFIED_COUNT = 1, GACHA_GUARANTEE_LOOP_COUNT = 2, GACHA_GUARANTEE_N_COUNT = 3, GACHA_GUARANTEE_LOOP_COUNT_WITH_CHILDS = 4, GACHA_GUARANTEE_N_COUNT_WITH_CHILDS = 5}
upval_0.GachaGuaranteeResetType, l_0_0 = l_0_0, {GACHA_GUARANTEE_RESET_NONE = 0, GACHA_GUARANTEE_RESET_ACTIVITY_CHANGE = 1}

