-- Decompiled using luadec 2.2 rev: 5d67c74 for Lua 5.3 from https://github.com/viruscamp/luadec
-- Command line: C:\Users\nikur\Documents\3.3.51_lua\MiHoYoBinData\MaterialExcelConfig.luac 

-- params : ...
-- function num : 0 , upvalues : upval_0
local l_0_0 = {}
l_0_0.FOOD_QUALITY_NONE = 0
l_0_0.FOOD_QUALITY_STRANGE = 1
l_0_0.FOOD_QUALITY_ORDINARY = 2
l_0_0.FOOD_QUALITY_DELICIOUS = 3
upval_0.FoodQualityType = l_0_0
upval_0.ItemUseOp, l_0_0 = l_0_0, {ITEM_USE_NONE = 0, ITEM_USE_ACCEPT_QUEST = 1, ITEM_USE_TRIGGER_ABILITY = 2, ITEM_USE_GAIN_AVATAR = 3, ITEM_USE_ADD_EXP = 4, ITEM_USE_RELIVE_AVATAR = 5, ITEM_USE_ADD_BIG_TALENT_POINT = 6, ITEM_USE_ADD_PERSIST_STAMINA = 7, ITEM_USE_ADD_TEMPORARY_STAMINA = 8, ITEM_USE_ADD_CUR_STAMINA = 9, ITEM_USE_ADD_CUR_HP = 10, ITEM_USE_ADD_ELEM_ENERGY = 11, ITEM_USE_ADD_ALL_ENERGY = 12, ITEM_USE_ADD_DUNGEON_COND_TIME = 13, ITEM_USE_ADD_WEAPON_EXP = 14, ITEM_USE_ADD_SERVER_BUFF = 15, ITEM_USE_DEL_SERVER_BUFF = 16, ITEM_USE_UNLOCK_COOK_RECIPE = 17, ITEM_USE_ADD_AVATAR_BIG_TALENT_POINT = 18, ITEM_USE_ADD_AVATAR_SMALL_TALENT_POINT = 19, ITEM_USE_OPEN_RANDOM_CHEST = 20, ITEM_USE_ADD_MAIN_AVATAR_BIG_TALENT_POINT = 22, ITEM_USE_ADD_MAIN_AVATAR_SMALL_TALENT_POINT = 23, ITEM_USE_MAKE_GADGET = 24, ITEM_USE_ADD_ITEM = 25}
upval_0.ItemUseTarget, l_0_0 = l_0_0, {ITEM_USE_TARGET_NONE = 0, ITEM_USE_TARGET_CUR_AVATAR = 1, ITEM_USE_TARGET_CUR_TEAM = 2, ITEM_USE_TARGET_SPECIFY_AVATAR = 3, ITEM_USE_TARGET_SPECIFY_ALIVE_AVATAR = 4, ITEM_USE_TARGET_SPECIFY_DEAD_AVATAR = 5}
upval_0.DocumentType, l_0_0 = l_0_0, {Book = 0, Video = 1}
upval_0.MaterialExpireType, l_0_0 = l_0_0, {CountDown = 1, DateTime = 2}

